const emphasisTerms = [
  "상태 신뢰성과 체감 성능",
  "상태 동기화",
  "화면 상태 흐름",
  "운영 안정성",
  "Live Activity 응답",
  "렌더링 병목",
  "출시 안정화 대응",
  "상태 지연",
  "화면 끊김",
  "운영 불안정성",
  "Local-First",
  "AsyncStream",
  "SwiftData",
  "ActivityKit",
  "Live Activity",
  "Dynamic Island",
  "Instruments",
  "Core Animation Commits",
  "GPU Hitch",
  "Cloud Tasks",
  "APNs push-to-start",
  "update token",
  "APNs/FCM 토큰 등록·갱신",
  "비동기 테스트",
  "@MainActor",
  "App Store",
  "Release",
  "한 방향 흐름",
  "유지보수성",
  "평균 6분대 피드백 루프",
  "잠재 결함 14%",
  "574.47초",
  "24%",
  "8.46초",
  "검증 한도 100000",
  "1000개 스테이지",
  "실패/복수 정답 0개",
  "검증된 스테이지 1000개",
  "검증된 스테이지",
  "정답이 하나인 스테이지 1000개",
  "정답이 하나인 스테이지",
  "정답이 하나인 퍼즐 1000개",
  "정답이 하나인 퍼즐",
  "정답 유일성 검증",
  "일관된 퍼즐 진행 흐름",
  "힌트와 완료 판정",
  "완료 판정",
  "로컬 진행 저장",
  "진행 저장",
  "서버 없이 동작",
  "서버 없이",
  "광고/구매 경계",
  "광고/구매",
  "입력 경계",
  "큰 보드 조작 경험",
  "큰 보드",
  "한 손가락 칠하기",
  "두 손가락 이동",
  "화면 이동/확대",
  "확대/축소",
  "미니맵 탐색",
  "미니맵 선택",
  "스테이지 품질",
  "생성 속도",
  "로컬 우선 경계",
  "구매 검증",
  "스테이지 팩",
  "진행 동기화",
  "핵심 플레이 흐름",
  "정답 검증 로직",
  "ViewModel/StateFlow",
  "suspend Repository",
  "Canvas 입력",
  "Canvas 기반 보드 입력",
  "Android 표준 상태 관리",
  "비동기 데이터 로딩",
  "작은 흐름",
  "작은 기능 흐름",
  "전면 포팅",
  "플랫폼 확장",
  "플랫폼 확장 설계",
  "플랫폼·배포 경계 확장",
  "Android MVP 확장",
  "상태 관리와 데이터 로딩 경계",
  "기술 경계",
  "기능 흐름을 구조화해 검증",
  "작은 기능 흐름을 먼저 닫고",
  "책임과 검증 기준",
  "퍼즐 데이터",
  "저장 형식에 의존하지 않게",
  "생명주기에 맞춰 상태를 읽도록",
  "생명주기에 맞춘 상태 연결",
  "테스트 가능한 구조",
  "JVM 테스트",
  "백엔드 데이터 소스",
  "작은 제품 흐름",
  "API 연동",
  "DB migration",
  "DB Migration",
  "CSV import",
  "CSV 데이터 Import",
  "GitHub Pages",
  "콘텐츠의 일관성과 유지보수성",
  "SPA fallback",
  "404.html",
].sort((a, b) => b.length - a.length);

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

const emphasisPattern = new RegExp(
  `(${emphasisTerms.map(escapeRegExp).join("|")})`,
  "g",
);

export function highlightPortfolioText(value: string) {
  return escapeHtml(value).replace(
    emphasisPattern,
    '<strong class="portfolio-emphasis">$1</strong>',
  );
}
